# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build.build_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false

      - name: Build
        id: build
        shell: bash
        run: |
          echo "Building"
          echo "build_id=12345" >> "$GITHUB_OUTPUT"
